CREATE TABLESPACE MONETIZATION DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/MONETIZATION.dbf' size 100M AUTOEXTEND ON;

CREATE USER MONETIZATION IDENTIFIED BY MONETIZATION DEFAULT TABLESPACE MONETIZATION TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON MONETIZATION;

GRANT CONNECT,RESOURCE, CREATE ANY VIEW TO MONETIZATION;

GRANT CREATE JOB TO MONETIZATION; 
