package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class AccessNetworkArea extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public Geo_Location_1 geo_Location_=new Geo_Location_1();
    
    public ArrayList< Location3GPP>location_3gpp =new ArrayList<Location3GPP>();
    
    public ArrayList< Location3GPP2>location_3gpp2 =new ArrayList<Location3GPP2>();
    
    public ArrayList< WiMAXLocation>wimMax_Location =new ArrayList<WiMAXLocation>();
    
    public ArrayList< WlanLocation>wlan_Location =new ArrayList<WlanLocation>();

    public AccessNetworkArea ()
    {
    }

    public AccessNetworkArea (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("geo_Location_"))
        {	
	        java.lang.Object j = soapObject.getProperty("geo_Location_");
	        this.geo_Location_ = new Geo_Location_1(j,__envelope);
        }
        if (soapObject.hasProperty("location_3gpp"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.location_3gpp = new ArrayList<Location3GPP>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("location_3gpp"))
	            {
                    java.lang.Object j =info.getValue();
	                Location3GPP j1= (Location3GPP)__envelope.get(j,Location3GPP.class);
	                this.location_3gpp.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("location_3gpp2"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.location_3gpp2 = new ArrayList<Location3GPP2>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("location_3gpp2"))
	            {
                    java.lang.Object j =info.getValue();
	                Location3GPP2 j1= (Location3GPP2)__envelope.get(j,Location3GPP2.class);
	                this.location_3gpp2.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("wimMax_Location"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.wimMax_Location = new ArrayList<WiMAXLocation>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("wimMax_Location"))
	            {
                    java.lang.Object j =info.getValue();
	                WiMAXLocation j1= (WiMAXLocation)__envelope.get(j,WiMAXLocation.class);
	                this.wimMax_Location.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("wlan_Location"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.wlan_Location = new ArrayList<WlanLocation>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("wlan_Location"))
	            {
                    java.lang.Object j =info.getValue();
	                WlanLocation j1= (WlanLocation)__envelope.get(j,WlanLocation.class);
	                this.wlan_Location.add(j1);
	            }
	        }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.geo_Location_!=null?this.geo_Location_:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=+1 && propertyIndex< + 1+this.location_3gpp.size())
        {
            return this.location_3gpp.get(propertyIndex-(+1));
        }
        if(propertyIndex>=+1+this.location_3gpp.size() && propertyIndex< + 1+this.location_3gpp.size()+this.location_3gpp2.size())
        {
            return this.location_3gpp2.get(propertyIndex-(+1+this.location_3gpp.size()));
        }
        if(propertyIndex>=+1+this.location_3gpp.size()+this.location_3gpp2.size() && propertyIndex< + 1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size())
        {
            return this.wimMax_Location.get(propertyIndex-(+1+this.location_3gpp.size()+this.location_3gpp2.size()));
        }
        if(propertyIndex>=+1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size() && propertyIndex< + 1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size()+this.wlan_Location.size())
        {
            return this.wlan_Location.get(propertyIndex-(+1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size()));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+location_3gpp.size()+location_3gpp2.size()+wimMax_Location.size()+wlan_Location.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "geo_Location_";
            info.namespace= "";
        }
        if(propertyIndex>=+1 && propertyIndex <= +1+this.location_3gpp.size())
        {
            info.type = Location3GPP.class;
            info.name = "location_3gpp";
            info.namespace= "";
        }
        if(propertyIndex>=+1+this.location_3gpp.size() && propertyIndex <= +1+this.location_3gpp.size()+this.location_3gpp2.size())
        {
            info.type = Location3GPP2.class;
            info.name = "location_3gpp2";
            info.namespace= "";
        }
        if(propertyIndex>=+1+this.location_3gpp.size()+this.location_3gpp2.size() && propertyIndex <= +1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size())
        {
            info.type = WiMAXLocation.class;
            info.name = "wimMax_Location";
            info.namespace= "";
        }
        if(propertyIndex>=+1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size() && propertyIndex <= +1+this.location_3gpp.size()+this.location_3gpp2.size()+this.wimMax_Location.size()+this.wlan_Location.size())
        {
            info.type = WlanLocation.class;
            info.name = "wlan_Location";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "AccessNetworkArea [geo_Location_=" + geo_Location_
				+ ", location_3gpp=" + location_3gpp + ", location_3gpp2="
				+ location_3gpp2 + ", wimMax_Location=" + wimMax_Location
				+ ", wlan_Location=" + wlan_Location + "]";
	}
}
