package com.elitecorelib.andsf.pojo;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class ANDSFWebServiceSoapBinding
{
    interface CLCIWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://10.106.1.45:8080/easyconnect/services/ANDSFWebService";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;
    public ANDSFWebServiceSoapBinding(){}

    public ANDSFWebServiceSoapBinding (IServiceEvents callback)
    {
        this.callback = callback;
    }
    public ANDSFWebServiceSoapBinding(IServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public ANDSFWebServiceSoapBinding(IServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public InitializeResponse InitializeRequest(final String userName,final String password,final String IMEI,final String deviceType,final String IMSI,final String MSISDN,final String feature ) throws java.lang.Exception
    {
        return (InitializeResponse)execute(new CLCIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://ws.andsf.elitecore.com/", "InitializeRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="userName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(userName!=null?userName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(password!=null?password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="IMEI";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(IMEI!=null?IMEI:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="deviceType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(deviceType!=null?deviceType:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="IMSI";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(IMSI!=null?IMSI:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="MSISDN";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(MSISDN!=null?MSISDN:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="feature";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(feature!=null?feature:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (InitializeResponse)getResult(InitializeResponse.class,__result,"InitializeResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< InitializeResponse>> InitializeRequestAsync(final String userName,final String password,final String IMEI,final String deviceType,final String IMSI,final String MSISDN,final String feature)
    {
        return executeAsync(new Functions.IFunc< InitializeResponse>() {
            public InitializeResponse Func() throws java.lang.Exception {
                return InitializeRequest( userName,password,IMEI,deviceType,IMSI,MSISDN,feature);
            }
        });
    }
    
    public PolicyResponse GetPolicyRequest(final String session,final String tag,final UeLocation ue_Location,final String HexToken,final String tz ) throws java.lang.Exception
    {
        return (PolicyResponse)execute(new CLCIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","ue_Location",new UeLocation().getClass());
                SoapObject __soapReq = new SoapObject("http://ws.andsf.elitecore.com/", "GetPolicyRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="session";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(session!=null?session:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="tag";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(tag!=null?tag:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="ue_Location";
                __info.type=UeLocation.class;
                __info.setValue(ue_Location!=null?ue_Location:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="HexToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(HexToken!=null?HexToken:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="tz";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(tz!=null?tz:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PolicyResponse)getResult(PolicyResponse.class,__result,"PolicyResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< PolicyResponse>> GetPolicyRequestAsync(final String session,final String tag,final UeLocation ue_Location,final String HexToken,final String tz)
    {
        return executeAsync(new Functions.IFunc< PolicyResponse>() {
            public PolicyResponse Func() throws java.lang.Exception {
                return GetPolicyRequest( session,tag,ue_Location,HexToken,tz);
            }
        });
    }
    
    public String GetSampleRequest(final String param1 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> GetSampleRequestAsync(final String param1)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetSampleRequest( param1);
            }
        });
    }

    
    protected java.lang.Object execute(CLCIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {
        return new java.lang.Exception(fault.faultstring);
    }
}


