package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;

import org.ksoap2.serialization.*;

import com.elitecorelib.andsf.exception.InvalidDataException;
import com.elitecorelib.andsf.utility.CustomConstant;
import com.elitecorelib.andsf.utility.CustomMessage;

import android.util.Log;

public class Location3GPP extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String EUTRA_CI;
    
    public String GERAN_CI;
    
    public String LAC;
    
    public String PLMN;
    
    public String TAC;
    
    public String UTRAN_CI;

    public Location3GPP (){
    	
    }

    public Location3GPP (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("EUTRA_CI"))
        {	
	        java.lang.Object obj = soapObject.getProperty("EUTRA_CI");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.EUTRA_CI = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.EUTRA_CI = (String)obj;
            }    
        }
        if (soapObject.hasProperty("GERAN_CI"))
        {	
	        java.lang.Object obj = soapObject.getProperty("GERAN_CI");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.GERAN_CI = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.GERAN_CI = (String)obj;
            }    
        }
        if (soapObject.hasProperty("LAC"))
        {	
	        java.lang.Object obj = soapObject.getProperty("LAC");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.LAC = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.LAC = (String)obj;
            }    
        }
        if (soapObject.hasProperty("PLMN"))
        {	
	        java.lang.Object obj = soapObject.getProperty("PLMN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.PLMN = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.PLMN = (String)obj;
            }    
        }
        if (soapObject.hasProperty("TAC"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TAC");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TAC = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.TAC = (String)obj;
            }    
        }
        if (soapObject.hasProperty("UTRAN_CI"))
        {	
	        java.lang.Object obj = soapObject.getProperty("UTRAN_CI");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.UTRAN_CI = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.UTRAN_CI = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.EUTRA_CI!=null?this.EUTRA_CI:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.GERAN_CI!=null?this.GERAN_CI:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.LAC!=null?this.LAC:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.PLMN!=null?this.PLMN:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.TAC!=null?this.TAC:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.UTRAN_CI!=null?this.UTRAN_CI:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EUTRA_CI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GERAN_CI";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LAC";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PLMN";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TAC";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UTRAN_CI";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "Location3GPP [EUTRA_CI=" + EUTRA_CI + ", GERAN_CI="
				+ GERAN_CI + ", LAC=" + LAC + ", PLMN=" + PLMN + ", TAC=" + TAC
				+ ", UTRAN_CI=" + UTRAN_CI + "]";
	}

	public void validate() throws InvalidDataException {
		
		if(this.PLMN == null || "".equals(this.PLMN)){
			Log.d(CustomConstant.ApplicationTag, "PLMN Should be mandatory if any 3GPP validity location is mentioned .");
			throw new InvalidDataException(CustomMessage.missingPLMN);
		}
		
		
	}
}
