package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class WlanLocation extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String BSSID;
    
    public String HESSID;
    
    public String SSID;

    public WlanLocation ()
    {
    }

    public WlanLocation (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("BSSID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("BSSID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.BSSID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.BSSID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("HESSID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("HESSID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.HESSID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.HESSID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("SSID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SSID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SSID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SSID = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BSSID!=null?this.BSSID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.HESSID!=null?this.HESSID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.SSID!=null?this.SSID:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BSSID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HESSID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SSID";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "WlanLocation [BSSID=" + BSSID + "\n HESSID=" + HESSID
				+ "\n SSID=" + SSID + "]";
	}
}
