package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class AccessNetworkInformationWLAN extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String authProtocols;
    
    public Boolean autoJoin=false;
    
    public String bssid;
    
    public String EAPTypeAuths;
    
    public String geoRadius;
    
    public Boolean hexPassworde=false;
    
    public String hssid;
    
    public String latitude;
    
    public String longtitude;
    
    public String networkMode;
    
    public String nodeName;
    
    public String password;
    
    public Boolean policyHotspot=false;
    
    public String SSIDName;
    
    public String securityType;
    
    public Integer signalLevel=0;
    
    public Boolean ssidHidden=false;
    
    public Boolean useWPAPSK=false;
    
    public String userName;

    public AccessNetworkInformationWLAN ()
    {
    }

    public AccessNetworkInformationWLAN (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("authProtocols"))
        {	
	        java.lang.Object obj = soapObject.getProperty("authProtocols");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.authProtocols = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.authProtocols = (String)obj;
            }    
        }
        if (soapObject.hasProperty("autoJoin"))
        {	
	        java.lang.Object obj = soapObject.getProperty("autoJoin");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.autoJoin = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.autoJoin = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("bssid"))
        {	
	        java.lang.Object obj = soapObject.getProperty("bssid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.bssid = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.bssid = (String)obj;
            }    
        }
        if (soapObject.hasProperty("EAPTypeAuths"))
        {	
	        java.lang.Object obj = soapObject.getProperty("EAPTypeAuths");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.EAPTypeAuths = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.EAPTypeAuths = (String)obj;
            }    
        }
        if (soapObject.hasProperty("geoRadius"))
        {	
	        java.lang.Object obj = soapObject.getProperty("geoRadius");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.geoRadius = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.geoRadius = (String)obj;
            }    
        }
        if (soapObject.hasProperty("hexPassworde"))
        {	
	        java.lang.Object obj = soapObject.getProperty("hexPassworde");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.hexPassworde = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.hexPassworde = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("hssid"))
        {	
	        java.lang.Object obj = soapObject.getProperty("hssid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.hssid = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.hssid = (String)obj;
            }    
        }
        if (soapObject.hasProperty("latitude"))
        {	
	        java.lang.Object obj = soapObject.getProperty("latitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.latitude = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.latitude = (String)obj;
            }    
        }
        if (soapObject.hasProperty("longtitude"))
        {	
	        java.lang.Object obj = soapObject.getProperty("longtitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.longtitude = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.longtitude = (String)obj;
            }    
        }
        if (soapObject.hasProperty("networkMode"))
        {	
	        java.lang.Object obj = soapObject.getProperty("networkMode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.networkMode = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.networkMode = (String)obj;
            }    
        }
        if (soapObject.hasProperty("nodeName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("nodeName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.nodeName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.nodeName = (String)obj;
            }    
        }
        if (soapObject.hasProperty("password"))
        {	
	        java.lang.Object obj = soapObject.getProperty("password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.password = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.password = (String)obj;
            }    
        }
        if (soapObject.hasProperty("policyHotspot"))
        {	
	        java.lang.Object obj = soapObject.getProperty("policyHotspot");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.policyHotspot = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.policyHotspot = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("SSIDName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SSIDName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SSIDName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SSIDName = (String)obj;
            }    
        }
        if (soapObject.hasProperty("securityType"))
        {	
	        java.lang.Object obj = soapObject.getProperty("securityType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.securityType = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.securityType = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signalLevel"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signalLevel");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signalLevel = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.signalLevel = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("ssidHidden"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ssidHidden");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ssidHidden = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.ssidHidden = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("useWPAPSK"))
        {	
	        java.lang.Object obj = soapObject.getProperty("useWPAPSK");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.useWPAPSK = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.useWPAPSK = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("userName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("userName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.userName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.userName = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.authProtocols!=null?this.authProtocols:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return autoJoin;
        }
        if(propertyIndex==2)
        {
            return this.bssid!=null?this.bssid:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.EAPTypeAuths!=null?this.EAPTypeAuths:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.geoRadius!=null?this.geoRadius:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return hexPassworde;
        }
        if(propertyIndex==6)
        {
            return this.hssid!=null?this.hssid:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.latitude!=null?this.latitude:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.longtitude!=null?this.longtitude:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.networkMode!=null?this.networkMode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.nodeName!=null?this.nodeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.password!=null?this.password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return policyHotspot;
        }
        if(propertyIndex==13)
        {
            return this.SSIDName!=null?this.SSIDName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.securityType!=null?this.securityType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return signalLevel;
        }
        if(propertyIndex==16)
        {
            return ssidHidden;
        }
        if(propertyIndex==17)
        {
            return useWPAPSK;
        }
        if(propertyIndex==18)
        {
            return this.userName!=null?this.userName:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 19;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authProtocols";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "autoJoin";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "bssid";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EAPTypeAuths";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "geoRadius";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "hexPassworde";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "hssid";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "latitude";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "longtitude";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "networkMode";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nodeName";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "password";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "policyHotspot";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SSIDName";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "securityType";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "signalLevel";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ssidHidden";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "useWPAPSK";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "userName";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "AccessNetworkInformationWLAN [authProtocols="
				+ authProtocols + "\n autoJoin=" + autoJoin + "\n bssid=" + bssid
				+ "\n EAPTypeAuths=" + EAPTypeAuths + "\n geoRadius=" + geoRadius
				+ "\n hexPassworde=" + hexPassworde + "\n hssid=" + hssid
				+ "\n latitude=" + latitude + "\n longtitude=" + longtitude
				+ "\n networkMode=" + networkMode + "\n nodeName=" + nodeName
				+ "\n password=" + password + "\n policyHotspot=" + policyHotspot
				+ "\n SSIDName=" + SSIDName + "\n securityType=" + securityType
				+ "\n signalLevel=" + signalLevel + "\n ssidHidden=" + ssidHidden
				+ "\n useWPAPSK=" + useWPAPSK + "\n userName=" + userName + "]";
	}
    
}
