package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DiscoveryInformation extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public AccessNetworkArea accessNetworkArea;
    
    public AccessNetworkInformationWLAN accessNetworkInformationWLAN;
    
    public Integer accessNetworkType=0;

    public DiscoveryInformation ()
    {
    }

    public DiscoveryInformation (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("accessNetworkArea"))
        {	
	        java.lang.Object j = soapObject.getProperty("accessNetworkArea");
	        this.accessNetworkArea = (AccessNetworkArea)__envelope.get(j,AccessNetworkArea.class);
        }
        if (soapObject.hasProperty("accessNetworkInformationWLAN"))
        {	
	        java.lang.Object j = soapObject.getProperty("accessNetworkInformationWLAN");
	        this.accessNetworkInformationWLAN = (AccessNetworkInformationWLAN)__envelope.get(j,AccessNetworkInformationWLAN.class);
        }
        if (soapObject.hasProperty("accessNetworkType"))
        {	
	        java.lang.Object obj = soapObject.getProperty("accessNetworkType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.accessNetworkType = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.accessNetworkType = (Integer)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.accessNetworkArea!=null?this.accessNetworkArea:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.accessNetworkInformationWLAN!=null?this.accessNetworkInformationWLAN:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return accessNetworkType;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = AccessNetworkArea.class;
            info.name = "accessNetworkArea";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = AccessNetworkInformationWLAN.class;
            info.name = "accessNetworkInformationWLAN";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "accessNetworkType";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "DiscoveryInformation [accessNetworkArea="
				+ accessNetworkArea + ", accessNetworkInformationWLAN="
				+ accessNetworkInformationWLAN + ", accessNetworkType="
				+ accessNetworkType + "]";
	}
}
