package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class InitializeResponse extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String responseCode;
    
    public String session;
    
    public TimeOfDay timeout;

    public InitializeResponse ()
    {
    }

    public InitializeResponse (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("responseCode"))
        {	
	        java.lang.Object obj = soapObject.getProperty("responseCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.responseCode = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.responseCode = (String)obj;
            }    
        }
        if (soapObject.hasProperty("session"))
        {	
	        java.lang.Object obj = soapObject.getProperty("session");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.session = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.session = (String)obj;
            }    
        }
        if (soapObject.hasProperty("timeout"))
        {	
	        java.lang.Object j = soapObject.getProperty("timeout");
	        this.timeout = (TimeOfDay)__envelope.get(j,TimeOfDay.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.responseCode!=null?this.responseCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.session!=null?this.session:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.timeout!=null?this.timeout:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "responseCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "session";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = TimeOfDay.class;
            info.name = "timeout";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
