package com.elitecorelib.andsf.pojo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 04-03-2015
//
//---------------------------------------------------


import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Location3GPP2 extends AttributeContainer implements KvmSerializable,Serializable
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public Hrpd hrpd;
    
    public Rat1X rat1x;

    public Location3GPP2 ()
    {
    }

    public Location3GPP2 (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("hrpd"))
        {	
	        java.lang.Object j = soapObject.getProperty("hrpd");
	        this.hrpd = (Hrpd)__envelope.get(j,Hrpd.class);
        }
        if (soapObject.hasProperty("rat1x"))
        {	
	        java.lang.Object j = soapObject.getProperty("rat1x");
	        this.rat1x = (Rat1X)__envelope.get(j,Rat1X.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.hrpd!=null?this.hrpd:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.rat1x!=null?this.rat1x:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = Hrpd.class;
            info.name = "hrpd";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = Rat1X.class;
            info.name = "rat1x";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }

	@Override
	public String toString() {
		return "Location3GPP2 [hrpd=" + hrpd + ", rat1x=" + rat1x + "]";
	}
}
